# -*- coding: utf-8 -*-
"""Code2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RR6ryHDUGUAfEUu9GaU0yLxGApDmCH6z
"""

a = int(input("Enter First Number :"))
b = int(input("Enter second Number :"))
print("Addition",a+b)
print("Subtraction",a-b)
print("Multiplication",a*b)
print("Division",a/b)