# -*- coding: utf-8 -*-
"""Code3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RR6ryHDUGUAfEUu9GaU0yLxGApDmCH6z
"""

a = input("Enter the sentence:")
b = a.replace('python','pythons')
print(b)