# -*- coding: utf-8 -*-
"""Code4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RR6ryHDUGUAfEUu9GaU0yLxGApDmCH6z
"""

Total = float(input("Enter Total Score:"))
if Total >= 90:
  grade = 'A Grade'
elif Total >= 80:
  grade = 'B Grade'
elif Total >= 70:
  grade = 'C Grade'
elif Total >= 60:
  grade = 'D Grade'
else:
  grade = 'Fail'
print(grade)