# -*- coding: utf-8 -*-
"""Code1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RR6ryHDUGUAfEUu9GaU0yLxGApDmCH6z
"""

s = input("Enter String :")
t = list(s)
del t[0]
t.pop()
t.reverse()
u = "".join(t)
print(u)